### ISSUE TITLE
Debug drawer width needs increased

### ISSUE THREAD

**Issue by JakeWharton** [JakeWharton/u2020#142]
When compared to internal on my Nexus 4, the drawer is not as wide as it should/could be. I want the full width (minus 56dp) on my N4.

**Comment by caseykulm** [comment]
Looks like that's because of the field `private static final int MIN_DRAWER_MARGIN = 64;`. That field could be changed to 0, and the user could be expected to provide a width of match_parent, and the layout_marginLeft themselves in the xml which would be the ScrimInsetsFrameLayout block in debug_activity_frame.xml. Or more simply the `MIN_DRAWER_MARGIN` field could be changed to 56dp if it is a more sensible general minimum margin.

**Comment by JakeWharton** [comment]
Ah, fair. The Material guidelines say 56dp but if the support lib uses 64dp I'm not going to mess with it.
