### ISSUE TITLE
Question on Debug Drawer and Internal Builds

### ISSUE THREAD

**Issue by cemo** [JakeWharton/u2020#213]
First of all I would like to thank you a million times for this project. I have a strong web background and you made me so fun to learn Android. However I can not understand something conceptually. Please correct me If I say something wrong.

An internal application is a kind of app which is specialised for testing before production. I found that debug drawer is quite useful and think that this should be part of not only `debug internal` application but also `release internal` application as well. 

A tester can easily spot error by log, check requests and response logs, use stetho to debug drawing issues etc... And also most important think is that they can switch stage and production API on the fly and can easily test backward compatibility etc... 

Am I missing something in this area? Why Debug Drawer is limited to debug builds although it is useful for `release internal` builds as well?

**Comment by mattprecious** [comment]
Yeah, I've been wanting to do this for a while. The main thing holding us back is that we only want a subset of the debug drawer to be included in the internal release builds. We have a lot of controls that can put the app into a broken state if you're not paying attention or if you're not aware of the inner workings of the app.

I've been toying around with the idea of a modular debug drawer that can be configured based on your build variant, but it's nowhere near ready.

If you're comfortable with all of your debug controls being in your internal release build, I think it's as simple as moving all the code to the `internal` source directory instead of the `internalDebug` directory.

**Comment by cemo** [comment]
I have already done same thing. There are some issues regarding `drawer as a separate library`. Jake already explained his thoughts on #186 but I am still considering to pulled out as a library as a good candidate. In this case all settings would turn into a separate gradle dependency and a user can easily switch to necessary dependency by only declaring in its application.

**Comment by JakeWharton** [comment]
Yeah, there's nothing wrong with it being a separate library. I did not want (and continue to not want) u2020's drawer to be a separate library.

When you turn something into a library you have to worry about designing the API to support all the use-cases that one would want and also have to maintain some sense of API stability with proper versioning. One nice thing about the drawer not being a library is that we can change whatever we want, whenever we want. Because it's such a feature-filled area of the app, it changes constantly for us. If it were a non-internal, non-debug component then I would probably prefer a library, but since it's solely for us (the developers of the app) to use I value the flexibility that not being a library affords.

Like Matt said, we've talked about a drawer for our `internalRelease` build before, and it will surely happen eventually internally and in u2020.
